<?php
/**
 * Asset file for blocks.js
 * This file is auto-generated by @wordpress/scripts or can be maintained manually
 */
return array(
    'dependencies' => array(
        'wc-blocks-registry',
        'wc-settings',
        'wp-element',
        'wp-html-entities',
        'wp-i18n',
    ),
    'version' => '1.0.0',
);
